#!/usr/bin/env bash
set -euo pipefail
# ============================================================
# setup.sh  –  Host-side one-time setup for slahmr-docker
# Run this ONCE before the first `make dev-build`.
# ============================================================

REPO_DIR="workspace/slahmr"
PREPROC_DIR="${REPO_DIR}/slahmr/preproc"

SMPL_DIR="${PREPROC_DIR}/data"
SMPL_FILE="basicModel_neutral_lbs_10_207_0_v1.0.0.pkl"
SMPL_PATH="${SMPL_DIR}/${SMPL_FILE}"
SMPL_LINK="${PREPROC_DIR}/${SMPL_FILE}"
SMPL_URL="https://raw.githubusercontent.com/classner/up/821a390fbf87a522fb327fc46736eda0326e2a06/models/3D/${SMPL_FILE}"

DEPS_ZIP_URL="https://www.dropbox.com/s/lmvma12doimd7bf/slahmr_dependencies.zip"
DEMO_ZIP_URL="https://www.dropbox.com/s/0m9y0zd7f3emsh9/slahmr_demo.zip"

HOST_CONFIG_DIR="configs"
HOST_CUSTOM_CFG="${HOST_CONFIG_DIR}/custom.yaml"
HOST_VIDEO_CFG="${HOST_CONFIG_DIR}/video.yaml"

ENTRYPOINT_DEV_SRC="entrypoint.dev.sh"
ENTRYPOINT_PROD_SRC="entrypoint.prod.sh"
ENTRYPOINT_DEV_DST="${REPO_DIR}/entrypoint.dev.sh"
ENTRYPOINT_PROD_DST="${REPO_DIR}/entrypoint.prod.sh"

log()  { echo "[INFO] $*"; }
warn() { echo "[WARN] $*"; }
err()  { echo "[ERROR] $*" >&2; }

require_repo() {
  if [ ! -d "${REPO_DIR}" ]; then
    err "${REPO_DIR} does not exist."
    log "Run: make init"
    exit 1
  fi

  if ! git -C "${REPO_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    err "${REPO_DIR} is not a valid git working tree."
    log "Run: make reinit"
    exit 1
  fi
}

prepare_host_dirs() {
  mkdir -p workspace
  mkdir -p data
  mkdir -p data/inputs
  mkdir -p "${HOST_CONFIG_DIR}"
  log "Host directories ensured."
}

# --------------------------------------------------------
# Copy entrypoint scripts into the source tree so the
# dev bind-mount can expose them inside the container.
# --------------------------------------------------------
copy_entrypoints() {
  if [ ! -f "${ENTRYPOINT_DEV_SRC}" ] || [ ! -f "${ENTRYPOINT_PROD_SRC}" ]; then
    err "entrypoint source files are missing in project root."
    exit 1
  fi

  cp "${ENTRYPOINT_DEV_SRC}"  "${ENTRYPOINT_DEV_DST}"
  cp "${ENTRYPOINT_PROD_SRC}" "${ENTRYPOINT_PROD_DST}"
  chmod +x "${ENTRYPOINT_DEV_DST}" "${ENTRYPOINT_PROD_DST}"
  log "entrypoint scripts copied to ${REPO_DIR}/"
}

# --------------------------------------------------------
# Download model weights
# --------------------------------------------------------
prepare_smpl_model() {
  mkdir -p "${SMPL_DIR}"

  if [ ! -f "${SMPL_PATH}" ]; then
    log "Downloading SMPL model..."
    echo "[INFO] Please accept the license: https://smpl.is.tue.mpg"
    wget -nc "${SMPL_URL}" -P "${SMPL_DIR}"
  else
    log "SMPL model already exists. Skipping download."
  fi

  if [ ! -f "${SMPL_PATH}" ]; then
    err "SMPL model file is still missing after download attempt: ${SMPL_PATH}"
    exit 1
  fi

  ln -sf "data/${SMPL_FILE}" "${SMPL_LINK}"
  log "SMPL symlink ensured: ${SMPL_LINK} -> data/${SMPL_FILE}"
}

download_and_extract_zip_if_missing() {
  local target_dir="$1"
  local zip_url="$2"
  local zip_name="$3"

  (
    cd "${REPO_DIR}"

    if [ -d "${target_dir}" ]; then
      log "${target_dir}/ already exists. Skipping."
      exit 0
    fi

    log "Downloading ${zip_name}..."
    wget -nc "${zip_url}" -O "${zip_name}"

    log "Extracting ${zip_name}..."
    unzip -oq "${zip_name}"
    rm -f "${zip_name}"
  )
}

# --------------------------------------------------------
# Ensure configs/ directory exists for custom.yaml and video.yaml
# --------------------------------------------------------
prepare_configs() {
  mkdir -p "${HOST_CONFIG_DIR}"

  if [ ! -f "${HOST_CUSTOM_CFG}" ]; then
    cat > "${HOST_CUSTOM_CFG}" <<'EOF'
# This file is generated by prepare_custom.sh at runtime.
# Placeholder so the bind-mount target exists at container start.
type: custom
seq: placeholder
root: /workspace/data
split: val
EOF
    log "Placeholder ${HOST_CUSTOM_CFG} created."
  else
    log "${HOST_CUSTOM_CFG} already exists. Keeping it."
  fi

  if [ ! -f "${HOST_VIDEO_CFG}" ]; then
    cat > "${HOST_VIDEO_CFG}" <<'EOF'
# This file is generated by prepare_video.sh at runtime.
# Placeholder so the bind-mount target exists at container start.
type: video
seq: placeholder
root: /workspace/data
split: val
EOF
    log "Placeholder ${HOST_VIDEO_CFG} created."
  else
    log "${HOST_VIDEO_CFG} already exists. Keeping it."
  fi
}

main() {
  log "Preparing host-side SLAHMR workspace..."
  require_repo
  prepare_host_dirs
  copy_entrypoints
  prepare_smpl_model
  download_and_extract_zip_if_missing "_DATA" "${DEPS_ZIP_URL}" "slahmr_dependencies.zip"
  download_and_extract_zip_if_missing "demo"  "${DEMO_ZIP_URL}" "slahmr_demo.zip"
  prepare_configs

  echo ""
  echo "[DONE] Host setup completed."
  echo ""
  echo "Recommended order:"
  echo "  make env-init"
  echo "  make init"
  echo "  make setup"
  echo "  make dev-build"
  echo "  make dev-up"
}

main
